"""
state.py - State definition for College Fest Management System AI Agents
"""

from typing import TypedDict, Optional, Dict, Any, List


class AgentState(TypedDict, total=False):
    """
    Represents the shared state passed between all agents in the LangGraph workflow.
    """
    # Core user input
    question: str                         # The user query, instruction, or issue
    user_role: str                        # "student", "coordinator", "judge", "sponsor", "admin"
    
    # Workflow routing & coordination
    route: str                            # Destination agent determined by supervisor
    history: List[str]                    # Agent trail / execution history
    
    # Domain specific context
    event_context: Optional[Dict[str, Any]] # Extra event details, if provided
    tool_outputs: Optional[Dict[str, Any]]  # Outputs from executed fest tools
    
    # Output and error tracking
    agent_response: str                   # Final response generated by the specialist agent
    error: Optional[str]                  # Any error message if something failed
    attempts: int                         # Number of attempts or retries
